# -*- coding: utf-8 -*-
"""app_notification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ny8sOFWiZwpoy3tYBSEreeHCo81Bf2Cf
"""

import datetime
import time
import requests
from plyer import notification

covidData= None
try:
  covidData=requests.gets("https://corona-rest-api.herokuapp.com/Api/india/")
except:
  #if the data is not fetch due to the lack of internet 
  print("Please check your internet")

if(covidData !=None):
  #converting the data in json format
  data= covidData.json()['Success']

  while(True):
    notification.notify(
        #title of the Notification
        title='COVID 19 Stats on {}'.format(datetime.date.today()),
        #the body of the notifcation:
        message="Total case : {totalcases }\n Today case:{todaycases}\n Total deaths:{totaldeaths}\n Total Active:{totalactive}".format(
            totalcases=data['cases'],
            todaycases=data['todaycases'],
            totaldeaths=data['totaldeaths'],
            Active=data['active']),

        app_icon = "Paomedia-Small-N-Flat-Bell.ico",
        timeout= 50
        )
    time.sleep(60*60*4)

